# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from group import Group

class Test123():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_123(self):
    self.open_home_page()
    self.login(username="admin", password="secret")
    self.open_groups_page()
    self.input_group_creation()
    self.fill_group_form(Group(name="rewfradsfds", header="dsagahsg", footer="dsagsg"))
    self.submit_group_creation()
    self.return_to_group_page()
    self.logout()

  def test_1234(self):
    self.open_home_page()
    self.login(username="admin", password="secret")
    self.open_groups_page()
    self.input_group_creation()
    self.fill_group_form(Group(name="", header="", footer=""))
    self.submit_group_creation()
    self.return_to_group_page()
    self.logout()

  def logout(self):
    self.driver.find_element(By.LINK_TEXT, "Logout").click()

  def return_to_group_page(self):
    self.driver.find_element(By.LINK_TEXT, "group page").click()

  def submit_group_creation(self):
    self.driver.find_element(By.NAME, "submit").click()

  def fill_group_form(self, group):
    self.driver.find_element(By.NAME, "group_name").click()
    self.driver.find_element(By.NAME, "group_name").send_keys(group.name)
    self.driver.find_element(By.NAME, "group_header").click()
    self.driver.find_element(By.NAME, "group_header").send_keys(group.header)
    self.driver.find_element(By.NAME, "group_footer").click()
    self.driver.find_element(By.NAME, "group_footer").send_keys(group.footer)

  def input_group_creation(self):
    self.driver.find_element(By.NAME, "new").click()

  def open_groups_page(self):
    self.driver.find_element(By.LINK_TEXT, "groups").click()

  def login(self, username, password):
    self.driver.find_element(By.NAME, "user").send_keys(username)
    self.driver.find_element(By.NAME, "pass").send_keys(password)
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def open_home_page(self):
    self.driver.get("http://localhost/addressbook/")
    self.driver.set_window_size(550, 694)
  
